================================================
Test cases for the ``7-base_geometry.py`` module
================================================

This module defines a class with a function that validated the value parameter passed to it
def integer_validator(self, name, value)


::
Calling the area method
>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()
>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented

::
Passing an int
>>> bg.integer_validator("name", 10)

::
Passing a string as value
>>> bg.integer_validator("name", "ten")
Traceback (most recent call last):
...
TypeError: name must be an integer

::
Passing 0 as value
>>> bg.integer_validator("name", 0)
Traceback (most recent call last):
...
ValueError: name must be greater than 0

::
Passing value less than 0
>>> bg.integer_validator("name", -1)
Traceback (most recent call last):
...
ValueError: name must be greater than 0

::
Passing extra arg for area()
>>> bg.area(1)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 2 were given

::
Passing a bool value
>>> bg.integer_validator("name", True)
Traceback (most recent call last):
...
TypeError: name must be an integer

::
Passing a float
>>> bg.integer_validator("name", 1.4)
Traceback (most recent call last):
...
TypeError: name must be an integer

::
Passng an empty value to integer_validator
>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

::
Passng only one value to integer_validator
>>> bg.integer_validator("name")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

::
Passng more the two value to integer_validator
>>> bg.integer_validator("name", 1, 2)
Traceback (most recent call last):
...
TypeError: integer_validator() takes 3 positional arguments but 4 were given

::
Passing a tuple
>>> bg.integer_validator("tuple", (1, 2))
Traceback (most recent call last):
...
TypeError: tuple must be an integer

::
Passing a list
>>> bg.integer_validator("list", [1, 2, 3])
Traceback (most recent call last):
...
TypeError: list must be an integer

::
Passing a dictionary
>>> bg.integer_validator("dict", {"key": "value"})
Traceback (most recent call last):
...    
TypeError: dict must be an integer

::
Passing a set
>>> bg.integer_validator("set", {"hello", "world"})
Traceback (most recent call last):
...
TypeError: set must be an integer

::
passing a frozenset()
>>> bg.integer_validator("frozenset", frozenset(["hello", "world"]))
Traceback (most recent call last):
...
TypeError: frozenset must be an integer

::
Passing a bytes object
>>> bg.integer_validator("bytes", b"bytes")
Traceback (most recent call last):
...
TypeError: bytes must be an integer

::
Passing a bytearray
>>> bg.integer_validator("bytearrays", bytearray(b"bytes"))
Traceback (most recent call last):
...
TypeError: bytearrays must be an integer
